### ISSUE TITLE
exception running apigrabber on SG...

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#28]
happened only once in evening and since then it has been happening. maybe another of API data instances. please check

```
future: <Task finished coro=<Apigrabber.crawl_region() done, defined at /apps/api/api.py:128> exception=UniqueViolationError('duplicate key value violates unique constraint
',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/apps/api/api.py", line 174, in crawl_region
    jobdate)
  File "/apps/api/api.py", line 120, in crawl_timeframe
    await self._db_insert(con, matches)
  File "/apps/api/api.py", line 72, in _db_insert
    """)
  File "/usr/local/lib/python3.5/site-packages/asyncpg/connection.py", line 170, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 255, in query (asyncpg/protocol/protocol.c:57341)
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
```

**Comment by schneefux** [comment]
#39
