### ISSUE TITLE
Unknown encoding error

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/apigrabber#31]
```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Apigrabber.crawl_region() done, defined at api.py:169> exception=LookupError('unknown encoding: EUC-TW',)>
Traceback (most recent call last):
  File "api.py", line 216, in crawl_region
    jobdate)
  File "api.py", line 149, in crawl_timeframe
    matches = await api.matches(region=region, params=params)
  File "vainsocial/apigrabber/crawler.py", line 79, in matches
    params)
  File "vainsocial/apigrabber/crawler.py", line 40, in _req
    return await response.json()
  File "vainsocial/apigrabber/venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 772, in json
    return loads(stripped.decode(encoding))
LookupError: unknown encoding: EUC-TW
```

**Comment by schneefux** [comment]
Did not appear again.
