### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/apigrabber#32]
```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Apigrabber.crawl_region() done, defined at api.py:169> exception=InFailedSQLTransactionError('aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert',)>
Traceback (most recent call last):
  File "api.py", line 216, in crawl_region
    jobdate)
  File "api.py", line 161, in crawl_timeframe
    await self._db_insert(con, matches, jobstart, region)
  File "api.py", line 108, in _db_insert
    ")")
  File "vainsocial/apigrabber/venv/lib/python3.6/site-packages/asyncpg/connection.py", line 170, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 255, in query (asyncpg/protocol/protocol.c:57341)
asyncpg.exceptions.InFailedSQLTransactionError: aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert
```

**Comment by schneefux** [comment]
reopen if still relevant after #39
